---
title: "Performance Hiking Trail: Baños Azules"
author: "RMiranda"
format: 
  html:
    theme: flatly
    page-layout: full
    toc: false
    self-contained: true
---

```{r}
#| label: setup
#| include: false

library(sf)
library(tidyverse)
library(leaflet)
library(bslib)
library(htmltools)
library(bsicons)
library(lubridate)
library(paletteer)
library(ggspatial)
library(units)

# --- CARGA Y CÁLCULOS ---
archivo_gpx <- "banos_azules.gpx"
track_sum <- st_read(archivo_gpx, layer = "tracks")
points <- st_read(archivo_gpx, layer = "track_points")

points$time <- as.POSIXct(points$time, format="%Y-%m-%dT%H:%M:%OSZ", tz="UTC")
points$time <- with_tz(points$time, tzone = "America/Santiago")

df_plot <- points %>% 
  select(track_seg_point_id, time, ele) %>%
  mutate(
    time_secs = as.numeric(difftime(time, lag(time), units = "secs")),
    dist_points = as.numeric(st_distance(geometry, lag(geometry), by_element = TRUE)),
    vel_kmh = (dist_points / 1000) / (time_secs / 3600),
    delta_ele = ele - lag(ele),
    pend_pct = (delta_ele / dist_points) * 100,
    dist_cum_km = cumsum(coalesce(dist_points, 0)) / 1000    
  )

# Lógica de tramos (Ida/Vuelta)
pos_max_ele <- df_plot %>% filter(time_secs == max(time_secs, na.rm = TRUE)) %>% slice(1) %>% pull(track_seg_point_id)

df_plot <- df_plot %>% mutate(Trayecto = ifelse(track_seg_point_id < pos_max_ele, "1. Ida", "2. Vuelta"))

#Static chart
# 1. OPTIMIZACIÓN DE SEGMENTOS (Más rápido y seguro para la columna geometry)
coords <- st_coordinates(df_plot)
n <- nrow(coords)

lineas_list <- lapply(1:(n-1), function(i) {
  st_linestring(coords[i:(i+1), ])
})
  
# Creamos el dataframe de segmentos heredando los datos de df_plot
df_segments_top <- df_plot[-1, ] # Quitamos el primer punto porque no tiene segmento previo
df_segments_top$geometry <- st_sfc(lineas_list, crs = 4326)
df_segments_top <- st_as_sf(df_segments_top)

# Métricas
obtener_metrics <- function(data) {
  list(
    inicio = format(min(data$time, na.rm=T), "%H:%M"),
    fin = format(max(data$time, na.rm=T), "%H:%M"),
    alt_max = round(max(data$ele, na.rm=T), 0),
    alt_min = round(min(data$ele, na.rm=T), 0),
    pend_avg = round(sum(data$delta_ele, na.rm=T) / sum(data$dist_points, na.rm=T)*100, 2)
  )
}


m_global <- obtener_metrics(df_plot)

kpi_resumen <- df_plot %>%
  st_drop_geometry() %>%
  group_by(Trayecto) %>%
  summarise(
    distancia_total_km = sum(dist_points, na.rm = TRUE) / 1000,
    tiempo_total_mins = sum(time_secs, na.rm = TRUE) / 60,
    velocidad_promedio_kmh = mean(vel_kmh, na.rm = TRUE),
    velocidad_maxima_kmh = max(vel_kmh, na.rm = TRUE),
    ascenso_acumulado_m = sum(delta_ele[delta_ele > 0], na.rm = TRUE),
    descenso_acumulado_m = sum(delta_ele[delta_ele < 0], na.rm = TRUE)
  )

kpi_velocidad <- df_plot %>%
  st_drop_geometry() %>%
  group_by(Trayecto) %>%
  summarise(
    # Métricas básicas
    vel_pro = mean(vel_kmh, na.rm = TRUE),
    vel_min   = min(vel_kmh, na.rm = TRUE),
    vel_max   = max(vel_kmh, na.rm = TRUE),
    vel_med  = median(vel_kmh, na.rm = TRUE),
    # Promedio recortado al 90% (elimina 5% de cada extremo)
    vel_rec90 = mean(vel_kmh, trim = 0.05, na.rm = TRUE))

kpi_pendiente <- df_plot %>%
  st_drop_geometry() %>%
  group_by(Trayecto) %>%
  summarise(
    # Pendientes Positivas (Ascenso)
    n_pos = sum(pend_pct > 0, na.rm = TRUE),
    pend_pos_avg = round(sum(delta_ele[pend_pct > 0], na.rm = TRUE)/
      sum(dist_points[delta_ele > 0], na.rm = TRUE) * 100,  2),
    # Pendientes Negativas (Descenso)
    n_neg = sum(pend_pct < 0, na.rm = TRUE),
    pend_neg_avg = round(sum(delta_ele[pend_pct < 0], na.rm = TRUE)/
      sum(dist_points[delta_ele < 0], na.rm = TRUE) * 100,  2)   
    )


# Segmentos para el mapa
df_segments <- df_plot %>%
  mutate(geom_prev = lag(geometry)) %>%
  filter(!st_is_empty(geom_prev) & !is.na(time_secs)) %>%
  rowwise() %>%
  mutate(geometry = st_sfc(st_linestring(rbind(st_coordinates(geometry), st_coordinates(geom_prev))))) %>%
  st_as_sf(crs = 4326)

m_ida    <- obtener_metrics(df_plot %>% filter(Trayecto == "1. Ida"))
m_vuelta <- obtener_metrics(df_plot %>% filter(Trayecto == "2. Vuelta"))

# Paletas
pal_vel <- colorNumeric("YlGnBu", domain = df_segments$vel_kmh)
pal_pend <- colorNumeric("RdYlGn", domain = df_segments$pend_pct, reverse = TRUE)

# Creamos una función para no repetir el código del mapa dos veces
crear_mapa <- function(datos) {
  # 1. Preparamos el texto del tooltip con todas las métricas juntas
  tooltip_texto <- ~lapply(paste0(
    "<b>DateTime:</b> ", format(time, "%d-%m-%Y %H:%M:%S")," <br>", 
    "<b>Tiempo transcurrido:</b> ", round(time_secs/60, 2)," min<br>", 
    "<b>Distancia:</b> ", round(dist_points, 1)," m<br>",     
    "<b>Velocidad:</b> ", round(vel_kmh, 2), " km/h<br>",
    "<b>Elevación:</b> ", round(delta_ele, 1), " m<br>",
    "<b>Altitud:</b> ", round(ele, 0), " msnm<br>",    
    "<b>Pendiente:</b> ", round(pend_pct, 1), "%"
  ), htmltools::HTML)

  # 2. Configuramos el efecto visual al pasar el cursor (hover)
  efecto_hover <- highlightOptions(
    weight = 9,           # Hace la línea más gruesa
    color = "white",    # La resalta en blanco
    bringToFront = TRUE,   # La trae al frente para que no la tapen otras líneas
    opacity = 0.3
      )

  leaflet(datos, height = 400) %>%
    addTiles() %>%
    
    # Capas de líneas usando 'label' en lugar de 'popup'
    addPolylines(
      color = ~pal_vel(vel_kmh), weight = 5, opacity = 0.9, group = "Velocidad (km/h)",
      label = tooltip_texto,
      highlightOptions = efecto_hover,
      labelOptions = labelOptions(
        style = list(
          "font-size" = "15px",         # <-- Aumenta el tamaño de la letra
          "padding" = "8px 12px",       # <-- Le da aire al texto
          "border-color" = "#2c3e50"    # <-- Un borde más elegante
        )
      )
    ) %>%
    addPolylines(
      color = ~pal_pend(pend_pct), weight = 5, opacity = 0.9, group = "Pendiente (%)",
      label = tooltip_texto,
      highlightOptions = efecto_hover,
      labelOptions = labelOptions(
      style = list(
        "font-size" = "15px",
        "padding" = "8px 12px",
        "border-color" = "#2c3e50"
        )
      )
    ) %>%
    
    # Controles de capas
    addLayersControl(
      baseGroups = c("Velocidad (km/h)", "Pendiente (%)"),
      options = layersControlOptions(collapsed = FALSE),
      position = "topleft"
    ) %>%
    
    # Leyendas sin 'group' para que siempre estén visibles, y con menos 'bins'
    addLegend(pal = pal_vel, values = ~vel_kmh, title = "Vel (km/h)", position = "bottomright", bins = 5) %>%
    addLegend(pal = pal_pend, values = ~pend_pct, title = "Pend (%)", position = "bottomright", bins = 5)
  
  }
```

```{=html}
<style>
/* 1. Reset base para homogeneizar motores de renderizado */
  *, *::before, *::after {
    box-sizing: border-box !important;
  }
  
  body {
    zoom: 90%; 
  }

  /* Solución alternativa exclusiva para Firefox (ya que no soporta la propiedad zoom) */
  @-moz-document url-prefix() {
    body {
      transform: scale(0.9);
      transform-origin: top center; 
      width: 111.11%;
    }
  }

  /* 2. Corrección de pantalla completa para Edge y Firefox */
  body, #quarto-content, .page-columns {
    width: 100% !important;
    overflow-x: hidden; /* Evita scrolls horizontales fantasmas en Mozilla */
  }

  .page-columns #quarto-content {
    padding-left: 25px !important;
    padding-right: 25px !important;
  }

  /* 3. Tus estilos existentes para los componentes bslib */
  /* Alineación de métricas */
.bslib-value-box {
  height: 220px !important;
  margin-bottom: 10px !important;
  }

  
  .bslib-value-box .value {
    font-size: 1.3rem !important;
  }

  .footer-formulas {
    margin-top: 50px;
    padding: 25px;
    background-color: #f8f9fa;
    border-radius: 8px;
    border: 1px solid #e9ecef;
    color: #34495e;
    font-size: 0.9em;
  }


/* Estilo para los títulos de sección */
.section-title {
    color: #2c3e50;
    font-weight: bold;
    border-bottom: 2px solid #18bc9c;
    padding-bottom: 10px;
    margin-top: 30px;
    margin-bottom: 20px;
}

.column-screen {
  max-width: 1400px; /* Ancho máximo ideal */
  margin-left: auto;
  margin-right: auto;
}

.figure-img {
    margin: 0;
    line-height: 1
}

/* Alineación de métricas */
.bslib-value-box {
  height: 220px !important;
  margin-bottom: 10px !important;
}

.bslib-value-box .showcase { font-size: 2.2rem !important}
.bslib-value-box .value-box-title { font-size: 1.6rem !important; ; font-weight: bold;}

/* Forzar que el mapa empiece pegado al tope de su columna */
.leaflet-container {
  height: 450px !important; 
  margin-top: 0px !important;
}

.static-plot-container {
  height: 450px; /* (220 x 2) + 10 de margen */
  overflow: hidden;
  border-radius: 12px;
  border: 1px solid #dee2e6;
  padding: 0px !important; /* Eliminamos el espacio interno */
  margin: 0px !important;
  display: block; /* Ayuda a centrar contenido */
  background-color: white;
  }

/* ELIMINAR EL ESPACIO DE LAS CAPAS INTERNAS DE QUARTO */
.static-plot-container .cell-output-display, 
.static-plot-container div, 
.static-plot-container p {
  margin: 0 !important;
  padding: 0 !important;
  line-height: 0 !important; /* Vital: elimina el espacio de "base de texto" bajo la imagen */
  display: block !important;
}

.static-plot-container img {
  width: 100% !important;
  height: 450px !important; /* Forzamos la altura total de la caja */
  object-fit: cover; /* Llena el espacio recortando lo sobrante */
  display: block !important;
  margin: 0 !important;
}

.footer-formulas {
  margin-top: 20px;
  padding-top: 10px;
  border-top: 1px solid #e9ecef;
  color: #7f8c8d;
  font-size: 0.9em;
  text-align: center;
}
</style>
```

:::::::::::::::: {.column-screen style="padding: 25px;"}
# 1. Resumen General 

::::::: grid
:::: g-col-7
::: {layout-ncol="2"}
```{r}
#| echo: false
value_box(
  title = "Tiempo Recorrido",
  value = paste0(round(sum(kpi_resumen$tiempo_total_mins),0) %/% 60, ":", round(sum(kpi_resumen$tiempo_total_mins),0) %% 60, " hrs"), # Reemplazar con tu variable
  showcase = bsicons::bs_icon("stopwatch"),
  theme = "danger",
  p("Horario Ida:", m_ida$inicio, " - ",  m_ida$fin),
  p("Horario Vuelta:", m_vuelta$inicio, " - ", m_vuelta$fin) 
)
```


```{r}
#| echo: false
value_box(
  title = "Distancia Total",
  value = paste(round(sum(kpi_resumen$distancia_total_km),1), "km"),
  showcase = bsicons::bs_icon("signpost-split"),
  theme = "warning",
  p("Recorrido ida:", kpi_resumen %>% filter(Trayecto == "1. Ida") %>% 
  pull(distancia_total_km) %>% round(2), "km"),
  p("Recorrido vuelta:", kpi_resumen %>% filter(Trayecto == "2. Vuelta") %>% 
  pull(distancia_total_km) %>% round(2), "km")
)
```
```{r}
#| echo: false
value_box(
  title = "Altitud Máxima",
  value = paste(m_global$alt_max, "msnm"),
  showcase = bsicons::bs_icon("chevron-double-up"),
  theme = "success",
  p(paste("Pendiente:", m_global$alt_max - m_global$alt_min, "m")),
  p(paste("Alt. mínima:", m_global$alt_min, "msnm"))
)
```

```{r}
#| echo: false
value_box(
  title = track_sum$name,
  value = format(min(points$time), "%d-%m-%Y"), # Reemplazar con tu variable
  showcase = bsicons::bs_icon("cloud-sun"),
  theme = "primary"
)

```
:::
::::

:::: g-col-5
::: static-plot-container
```{r}
#| echo: false
#| message: false
#| warning: false
#| fig-width: 8.5
#| fig-height: 4.7
#| dpi: 150

# --- LÓGICA DE PADDING ---
bbox <- st_bbox(df_segments_top)
x_range <- bbox$xmax - bbox$xmin
y_range <- bbox$ymax - bbox$ymin

# Aumentamos el padding para que los elementos respiren en este nuevo tamaño
expand_x <- 0.10 
expand_y <- 0.10 

ggplot(df_segments_top) +
  annotation_map_tile(type = "osm", zoom = 14, alpha = 0.8) +
  geom_sf(aes(color = ele), size = 2, lineend = "round") +
  scale_color_viridis_c(
    option = "viridis", direction = -1, name = "Altitud\n(msnm)",
    guide = guide_colorbar(
      barwidth = unit(0.5, "cm"), 
      barheight = unit(3, "cm")
    )
  ) +
  coord_sf(
    xlim = c(bbox$xmin - x_range * expand_x, bbox$xmax + x_range * expand_x),
    ylim = c(bbox$ymin - y_range * expand_y, bbox$ymax + y_range * expand_y),
    expand = FALSE 
  ) + 
  theme_void() +
  theme(
    plot.margin = margin(0, 0, 0, 0),
    legend.position = c(0.9, 0.5), # Ajustada para el nuevo ancho
    legend.background = element_rect(fill = alpha("white", 0.7), color = "#bdc3c7"),
    legend.margin = margin(4, 4, 4, 4),
    legend.title = element_text(size = 9, face = "bold"),
    legend.text = element_text(size = 7),
    panel.spacing = unit(0, "lines")

  ) +
  annotation_scale(
    location = "br", 
    width_hint = 0.15, 
    text_size = 2.5 # Tamaño fijo pequeño
    #pad_x = unit(0.3, "cm"), 
    #pad_y = unit(0.3, "cm")
  ) + 
  annotation_north_arrow(
    location = "br", 
    pad_x = unit(0.6, "cm"), 
    pad_y = unit(0.8, "cm"),
    height = unit(0.9, "cm"), 
    width = unit(0.7, "cm"),
    style = north_arrow_orienteering(text_size = 5)
  )
```
:::
::::
:::::::

# 2.  Mapas Interactivos de Trayecto

::::::{.panel-tabset}
# Ruta Ida

::::: grid

::: g-col-4
```{r}
#| echo: false
# Filtrar datos específicos de Ida para simplificar las llamadas
vel_ida <- kpi_velocidad %>% filter(Trayecto == "1. Ida")
pend_ida <- kpi_pendiente %>% filter(Trayecto == "1. Ida")

value_box(
  title = "Velocidad Ida",
  value = paste("x̄ = ",round(vel_ida$vel_pro, 2), "km/h"),
  showcase = bsicons::bs_icon("signpost"),
  theme = "info",
  # Subsección 1: Mínimo y Máximo
  p(HTML(paste0("<b>Mín:</b> ", round(vel_ida$vel_min, 2), " km/h | <b>Máx:</b> ", round(vel_ida$vel_max, 2), " km/h")), style = "font-size: 1rem;"),
  # Subsección 2: Mediana y Promedio Recortado
  p(HTML(paste0("<b>Med:</b> ", round(vel_ida$vel_med, 2), " km/h | <b>x̄₉₀:</b> ", round(vel_ida$vel_rec90, 2), " km/h")), style = "font-size: 1rem;")
)

# CAJA 2: PENDIENTE (IDA)
value_box(
  title = "Pendiente Ida",
  value = paste(m_ida$pend_avg, "%"),
  showcase = bsicons::bs_icon("arrow-up-right-circle"),
  theme = "warning",
  # Subsección 1: Pendientes Positivas (Ascensos)
  p(HTML(paste0("<b>Pend + : Ptos </b> ", pend_ida$n_pos, " | x̄: ", pend_ida$pend_pos_avg, "% ")), style = "font-size: 1rem;"),
  # Subsección 2: Pendientes Negativas (Pequeñas bajadas/descansos en la ida)
  p(HTML(paste0("<b>Pend - : ptos </b> ", pend_ida$n_neg, " | x̄: ", pend_ida$pend_neg_avg, "% ")), style = "font-size: 1rem;")
)
```
:::

::: g-col-8
```{r}
#| echo: false
crear_mapa(df_segments %>% filter(Trayecto == "1. Ida"))
```
:::

:::::
::::::

:::::: {.panel-tabset}
# Ruta Vuelta

::::: grid

::: g-col-8
```{r}
#| echo: false
crear_mapa(df_segments %>% filter(Trayecto == "2. Vuelta"))
```
:::

::: g-col-4
```{r}
#| echo: false

# Filtrar datos específicos de Vuelta
vel_vta <- kpi_velocidad %>% filter(Trayecto == "2. Vuelta")
pend_vta <- kpi_pendiente %>% filter(Trayecto == "2. Vuelta")

# CAJA 1: PENDIENTE (VUELTA)

value_box(
  title = "Pendiente Vuelta",
  value = paste(m_vuelta$pend_avg, "%"),
  showcase = bsicons::bs_icon("arrow-down-left-circle"),
  theme = "success",
  # Subsección 1: Pendientes Negativas (Pequeñas bajadas/descansos en la ida)
  p(HTML(paste0("<b>Pend - : ptos </b> ", pend_vta$n_neg, " | x̄: ", pend_vta$pend_neg_avg, "% ")), style = "font-size: 1rem;"),
    # Subsección 2: Pendientes Positivas (Ascensos)
  p(HTML(paste0("<b>Pend + : Ptos </b> ", pend_vta$n_pos, " | x̄: ", pend_vta$pend_pos_avg, "% ")), style = "font-size: 1rem;")
)

# CAJA 2: VELOCIDAD (VUELTA)

value_box(
  title = "Velocidad Vuelta",
  value = paste("x̄ = ",round(vel_vta$vel_pro, 2), "km/h"),
  showcase = bsicons::bs_icon("signpost", style = "color: blue; transform: rotateY(180deg); display: inline-block;"),
  theme = "info",
  # Subsección 1: Mínimo y Máximo
  p(HTML(paste0("<b>Mín:</b> ", round(vel_vta$vel_min, 2), " km/h | <b>Máx:</b> ", round(vel_vta$vel_max, 2), " km/h")), style = "font-size: 1rem;"),
  # Subsección 2: Mediana y Promedio Recortado
  p(HTML(paste0("<b>Med:</b> ", round(vel_vta$vel_med, 2), " km/h | <b>x̄₉₀:</b> ", round(vel_vta$vel_rec90, 2), " km/h")), style = "font-size: 1rem;")
)
```
:::
:::::
::::::

::: {.footer-formulas}

Las métricas presentadas en este reporte se calculan utilizando las siguientes fórmulas:

::::: grid

::: g-col-6
**Velocidad ($km/h$):**
$$\text{Velocidad} = \frac{\text{Distancia (m)} / 1000}{\text{Tiempo (s)} / 3600}$$
:::

::: g-col-6
**Pendiente (%):**
$$\text{Pendiente} = \left( \frac{\Delta \text{Elevación (m)}}{\text{Distancia (m)}} \right) \times 100$$
:::
:::::

:::
::::::::::::::::
